apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-client-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: http2-client
  template:
    metadata:
      labels:
        app: http2-client
    spec:
      containers:
        - name: http2-client-container
          image: localhost:5000/http2-client:latest  