apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http2-server
  template:
    metadata:
      labels:
        app: http2-server
    spec:
      containers:
        - name: http2-server-container
          image: localhost:5000/http2-server:latest
          ports:
            - containerPort: 8000
